<?php

declare(strict_types=1);

use Basecom\SpeculationRulesToolbox\Model\Config;
use Basecom\SpeculationRulesToolbox\ViewModel\SpeculationRules;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var SpeculationRules $speculationRules */

$speculationRules = $viewModels->require(SpeculationRules::class);

// Only render on homepage
if (!$speculationRules->isHomepage()) {
    return;
}

/** @var Config $speculationRules */
$customLinksEnabled = $speculationRules->isHomepageCustomLinksEnabled();
$dynamicTargetsEnabled = $speculationRules->isHomepageDynamicTargetsEnabled();

if (!$customLinksEnabled || !$dynamicTargetsEnabled) {
    // Early return if no relevant settings are enabled
    return;
}

$preloadTypeCustom = $speculationRules->getHomepagePreloadTypeCustom();
$customLinksArray = $speculationRules->getHomepageCustomLinks();
$preloadTypeDynamic = $speculationRules->getHomepagePreloadTypeDynamic();
$cssSelector = $speculationRules->getHomePageCssSelector();
$concurrentPreloads = $speculationRules->getHomepageConcurrentPreloads();
?>

<?= /** @noEscape */ $block->getChildBlock('speculationrules.homepage.script')
    ->setData('customLinksEnabled', $customLinksEnabled)
    ->setData('dynamicTargetsEnabled', $dynamicTargetsEnabled)
    ->setData('preloadTypeCustom', $preloadTypeCustom)
    ->setData('customLinksArray', $customLinksArray)
    ->setData('preloadTypeDynamic', $preloadTypeDynamic)
    ->setData('cssSelector', $cssSelector)
    ->setData('concurrentPreloads', $concurrentPreloads)
    ->toHtml();
?>
